- name: Get Debian version
  become: true
  command: chroot {{ vyos_install_root }} awk 'match($0, /VERSION=.*\((\w+)\)/, version) { print version[1] }' /etc/os-release
  register: debian_version
- name: Set VyOS branch name crux
  set_fact:
    vyos_branch: "crux"
  when: vyos_version is regex("^1\.2.*$")
- name: Put debian.list
  become: true
  copy:
    src: "files/debian.list.{{ debian_version.stdout }}"
    dest: "{{ vyos_install_root }}/etc/apt/sources.list.d/debian.list"
- name: backup resolv.conf
  become: true
  command: mv {{ vyos_install_root }}/etc/resolv.conf /tmp/resolv.conf
- name: add nameserver settings to chroot
  become: true
  copy:
    src: "files/resolv.conf"
    dest: "{{ vyos_install_root }}/etc/resolv.conf"
- name: apt-get update
  become: true
  command: chroot {{ vyos_install_root }} apt-get update
- name: Install cloud-init
  become: true
  command: chroot {{ vyos_install_root }} apt-get -t {{ vyos_branch | default('current') }} install -y cloud-init cloud-utils
- name: apt-get clean
  become: true
  command: chroot {{ vyos_install_root }} apt-get clean
- name: delete apt lists from cache
  become: true
  command: chroot {{ vyos_install_root }} rm -rf /var/lib/apt/lists/
- name: Delete debian.list
  become: true
  file:
    path: "{{ vyos_install_root }}/etc/apt/sources.list.d/debian.list"
    state: absent
- name: Create cfg.d dir
  become: true
  file:
    path: "{{ vyos_install_root }}/etc/cloud/cloud.cfg.d/"
    state: directory
    mode: 0755
- name: Put datasource_list.cfg
  become: true
  template:
    src: 90_dpkg.cfg.j2
    dest: "{{ vyos_install_root }}/etc/cloud/cloud.cfg.d/90_dpkg.cfg"
- name: run dpkg-reconfigure cloud-init
  become: true
  command: chroot {{ vyos_install_root }} dpkg-reconfigure -f noninteractive cloud-init
- name: Disable config-stage modules
  become: true
  copy:
    src: "files/90_disable_config_stage.cfg"
    dest: "{{ vyos_install_root }}/etc/cloud/cloud.cfg.d/90_disable_config_stage.cfg"
  when:
    - cloud_init_disable_config
- name: restore original resolv.conf
  become: true
  command: mv /tmp/resolv.conf {{ vyos_install_root }}/etc/resolv.conf
- name: change /etc/network/interfaces to include config from Cloud-Init
  become: true
  command: chroot {{ vyos_install_root }} sed -i 's/source-directory \/etc\/network\/interfaces.d/source \/etc\/network\/interfaces.d\/*/g' /etc/network/interfaces
  when: vyos_version is regex("^1\.2.*$")
